public enum SkillID
{

    SKILL_ID_SLIME_STRIKE = 0,
    SKILL_ID_TOUSAND_NEEDLE = 1,
    SKILL_ID_HEAL = 2,
    SKILL_ID_TRAP_BITE = 3,
    SKILL_ID_SPIKE_ROLLING = 4,
    SKILL_ID_CACTUS_LARIAT = 5,
    SKILL_ID_NEEDLE_SHOT_1000 = 6,
    SKILL_ID_ENERGY_CACTUS = 7,
    SKILL_ID_POISON_NEEDLE = 8,
    SKILL_ID_TREASURE_CRUNCH = 9,
    SKILL_ID_FIRE_BREATH = 10,
    SKILL_ID_ICE_BREATH = 11,
    SKILL_ID_THUNDER_BREATH = 12,
    SKILL_ID_MUSH_CRUSHER = 13,
    SKILL_ID_FIRE_BURST = 14,
    SKILL_ID_AQUA_SLASH = 15,
    SKILL_ID_FROST_BITE = 16,
    SKILL_ID_SLIME_WAVE = 17,
    SKILL_ID_PSYCO_LASER = 18,
}
