// EffectType.cs
public enum EffectID
{
    None,
    EFFECT_ID_EXPLOSION_SMALL,
    EFFECT_ID_EXPLOSION_BIG,
    EFFECT_ID_FIRE_HIT,
    EFFECT_ID_FIRE_BREATH,
    EFFECT_ID_FIRE_BALL,
    EFFECT_ID_WATER_SPLASH,
    EFFECT_ID_SPARK,
    EFFECT_ID_SLIME_SPLASH,
    EFFECT_ID_MIMIC_BITE
}
