// EffectType.cs
public enum EffectID
{
    None,
    EFFECT_ID_EXPLOSION_SMALL = 1,
    EFFECT_ID_EXPLOSION_BIG = 2,
    EFFECT_ID_FIRE_HIT = 100,
    EFFECT_ID_FIRE_BREATH = 101,
    EFFECT_ID_FIRE_BALL,
    EFFECT_ID_WATER_SPLASH = 200,
    EFFECT_ID_SPARK = 300,
    EFFECT_ID_BEAM = 350,
    EFFECT_ID_SLIME_SPLASH = 400,
    EFFECT_ID_MIMIC_BITE = 500,
    EFFECT_ID_GROUND_HIT = 600,
    EFFECT_ID_AURA_A = 700,
}
